TM-100 Changing opportunities to opportunity when only one opportunity
SkillsFundingAgency/das-levy-transfer-matching-web pull request #115
Opened 2021-11-09 09:58 UTC by ConorTill

2021-11-10 10:21 UTC, sscaife requested changes

2021-11-10 10:21 UTC, sscaife commented on src/SFA.DAS.LevyTransferMatching.Web/Views/Opportunities/Index.cshtml
> +            @if (Model.Opportunities.Count() == 1)
@(Model.Opportunities.Count() == 1 ? "opportunity" : "opportunities") is cleaner

2021-11-10 10:37 UTC, sscaife approved these changes

2021-11-11 13:33 UTC, chrisfoster76 approved these changes

2021-11-16 09:27 UTC, merged