MAP-215 100% match applications
SkillsFundingAgency/das-levy-transfer-matching-web pull request #196
Opened 2023-07-13 09:37 UTC by jasonalexander-ja

Added nullable boolean `AutoApproveFullMatches` to `CreateViewModel` and `CreatePledgeCacheItem`, as well as the relevant page changes, endpoints, and classes to allow this to be accessed and updated.

2023-08-01 15:38 UTC, ogrwill requested changes

2023-08-01 15:38 UTC, ogrwill commented on src/SFA.DAS.LevyTransferMatching.Web/appsettings.json
This change isn't necessary.

2023-08-02 08:27 UTC, jasonalexander-ja commented on src/SFA.DAS.LevyTransferMatching.Web/Properties/launchSettings.json
Removed, sorry.

2023-08-02 08:27 UTC, jasonalexander-ja commented on src/SFA.DAS.LevyTransferMatching.Web/appsettings.json
Removed, sorry.

2023-08-02 09:01 UTC, ogrwill approved these changes

2023-08-02 09:45 UTC, merged